# Unit: rustkube-node test cluster — rkmaster1 + rknode1.
#
# ISOLATION RULE: rustkube's real control plane owns vmid 2000-2002
# (master1/2/3.g8.lo, 192.168.8.51-.53) and may expand upward from 2003.
# rustkube-node tests therefore use the TOP of the automation range:
# vmid 2090-2099, IPs 192.168.8.96+. Never point test kubelets at the real
# masters.
#
# Provisioning is done ENTIRELY in cloud-init user_data (the proven rustkube
# pattern) — no dependency on post-boot SSH before install. rkmaster1 runs a
# single-node fastetcd + rustkube control plane (plaintext); rknode1 runs
# CRI-O + the rustkube-node kubelet/kube-proxy pointed at rkmaster1.
#
#   export PROXMOX_API_TOKEN='terraform-svc@pve!rustkube-node=<secret>'
#   terragrunt apply
#
# vm_ids/IPs/MACs/hostnames verified free against live qm list + MicroDNS.

include "root" {
  path = find_in_parent_folders("root.hcl")
}

terraform {
  source = "git::ssh://git@github.com/glennswest/terraform-modules.git//modules/proxmox-fedora-vm?ref=v0.3.0"
}

locals {
  ssh_key   = trimspace(file(pathexpand("~/.ssh/id_rsa.pub")))
  master_ip = "192.168.8.98"

  # Control-plane PKI (generated by deploy/gen-pki.sh; gitignored). Injected via
  # cloud-init so the apiserver serves TLS and the node authenticates with a
  # client cert. Run deploy/gen-pki.sh before the first apply.
  pki = "${get_terragrunt_dir()}/pki"

  # Pinned released artifacts — the latest at rebuild time.
  fastetcd_rpm_url      = "https://github.com/glennswest/fastetcd/releases/download/v1.0.4/fastetcd-1.0.4-1.x86_64.rpm"
  rustkube_rpm_url      = "https://github.com/glennswest/rustkube/releases/download/v0.7.32/kubernetes-rs-0.7.32-1.x86_64.rpm"
  rustkube_node_rpm_url = "https://github.com/glennswest/rustkube-node/releases/download/v0.2.1/rustkube-node-0.2.1-1.fc43.x86_64.rpm"
}

inputs = {
  dns_zone_id        = "9bed60c8-1664-4183-88f9-a1a21b927edc" # g8.lo
  ci_ssh_public_keys = [local.ssh_key]
  tags               = ["terraform", "fedora", "rustkube-node"]

  vm_datastore      = "test-lvm-thin"
  snippet_datastore = "terraform-snippets"

  vms = {
    # Throwaway control plane for node-level testing.
    rkmaster1 = {
      vm_id  = 2090
      mac    = "BC:24:11:08:00:08"
      ip     = local.master_ip
      cores  = 2
      memory = 4096
      user_data = templatefile("${get_terragrunt_dir()}/templates/master-user-data.yaml.tftpl", {
        hostname         = "rkmaster1"
        fqdn             = "rkmaster1.g8.lo"
        ci_user          = "fedora"
        ssh_keys         = [local.ssh_key]
        node_ip          = local.master_ip
        fastetcd_rpm_url = local.fastetcd_rpm_url
        rustkube_rpm_url = local.rustkube_rpm_url
        # Control-plane PKI, injected into cloud-init write_files.
        ca_crt        = file("${local.pki}/ca.crt")
        ca_key        = file("${local.pki}/ca.key")
        sa_key        = file("${local.pki}/sa.key")
        apiserver_crt = file("${local.pki}/apiserver.crt")
        apiserver_key = file("${local.pki}/apiserver.key")
        cm_crt        = file("${local.pki}/controller-manager.crt")
        cm_key        = file("${local.pki}/controller-manager.key")
        sched_crt     = file("${local.pki}/scheduler.crt")
        sched_key     = file("${local.pki}/scheduler.key")
        admin_crt     = file("${local.pki}/admin.crt")
        admin_key     = file("${local.pki}/admin.key")
      })
    }
    # The node under test (kubelet + CRI-O from the rustkube-node packages).
    rknode1 = {
      vm_id  = 2091
      mac    = "BC:24:11:08:00:09"
      ip     = "192.168.8.99"
      cores  = 2
      memory = 4096
      user_data = templatefile("${get_terragrunt_dir()}/templates/node-user-data.yaml.tftpl", {
        hostname             = "rknode1"
        fqdn                 = "rknode1.g8.lo"
        ci_user              = "fedora"
        ssh_keys             = [local.ssh_key]
        apiserver_url        = "https://${local.master_ip}:6443"
        rustkube_node_rpm_url = local.rustkube_node_rpm_url
        # CA + node client-cert kubeconfig + :10250 server token.
        ca_crt             = file("${local.pki}/ca.crt")
        kubelet_kubeconfig = file("${local.pki}/kubelet.kubeconfig")
        server_token       = trimspace(file("${local.pki}/kubelet-server-token"))
      })
    }
  }
}
